### ISSUE TITLE
Script doesn't exit

### ISSUE THREAD

**Issue by timdonovanuk** [fire1ce/DDNS-Cloudflare-Bash#12]
Love the script, thank you! My only question is when you run it, it doesn't actually seem to exit? It just hangs. Not sure how that impacts when running under crontab (bunch of zombie processes?) 

Cheers!

**Comment by timdonovanuk** [comment]
Oh my mistake, it does exit...it just doesn't look like it.....weird

**Comment by fire1ce** [comment]
@timdonovanuk could you close the issue?

**Comment by timdonovanuk** [comment]
Sure but the script doesn't cleanly return to bash as shown in my screenshot. I had a quick look why but it wasn't immediately obvious to me. Any other scripts I run cleanly return to a bash prompt.

**Comment by fire1ce** [comment]
add `exit 0` to the end of the script. Rerun it and tell me if it solved the problem.

**Comment by timdonovanuk** [comment]
Nope that didn't work. But no worries, just a weird quirk, the script still runs 100% fine, thanks :)
