### ISSUE TITLE
Multiple A records not wokring.

### ISSUE THREAD

**Issue by dbline** [fire1ce/DDNS-Cloudflare-Bash#17]
Multiple A records is not working.

Love it in general though, Thank you!

ubuntu@dtest4:~$ sudo /usr/local/bin/update-cloudflare-dns.sh
==> 2023-08-24 00:10:15
==> Internal eth0 IP is: 172.31.173.179
==> DNS record IP of redis.bob.us is 172.31.173.179, no changes needed.
==> DNS record of  db.bob.us is: 172.31.161.143. Trying to update...
{"success":false,"errors":[{"code":10000,"message":"PUT method not allowed for the api_token authentication scheme"}]}
Error! Update failed

For now I am just running 2 scripts instead of just one.  It would be nice to fix it though.

Thanks,  DL

ps I scrubbed my domain names for privacy/security

**Comment by fire1ce** [comment]
you have space in you config after the comma between the domains

```shell
dns_record="ddns.example.com,ddns2.example.com"
```

**Comment by aybab2** [comment]
Having same issue.  Does the conf need comma separated list of zone ID's?

**Comment by aybab2** [comment]
https://github.com/fire1ce/DDNS-Cloudflare-Bash/issues/25#issue-2281059659
