### ISSUE TITLE
Message says "success" but the record not updated

### ISSUE THREAD

**Issue by switit** [fire1ce/DDNS-Cloudflare-Bash#20]
I'm using this script on my Seagate NAS box with Linux 6.1.28-sc armv6l. When the script is executed, the returned message is as below:
`root@Seagate-xxxxx:~# update-cloudflare-dns.sh
/usr/local/bin/update-cloudflare-dns.sh: line 13: /dev/fd/62: No such file or directory
==> 2023-12-22 08:55:08
==> External IP is: xx.x.xx.xx
/usr/local/bin/update-cloudflare-dns.sh: line 129: [: ==: unary operator expected
==> DNS record of xxx.xxx.com is: . Trying to update...
==> Success!
==> xxx.xxx.com DNS Record updated to: xx.xx.xx.xx, ttl: 120, proxied: true`
So, there are some errors but the last 2 lines seems to indicate a successful record updated. When I check the actual dns record at Cloudflare, it remains unchanged.

The aip token is verified to work. What may be the issue here?

**Comment by fire1ce** [comment]
by the errors you don't have bash. you have sh. 
the script should be run with bash.
if you do have bash, check permissions, and try to set locations manually. 
This is not a script issue, there for closing  it.
