### ISSUE TITLE
API Authentication Error

### ISSUE THREAD

**Issue by vaughngx4** [fire1ce/DDNS-Cloudflare-Bash#3]
I've run the script and gotten the following in my output(separately):
```
update-cloudflare-dns.sh: line 110: [: ==: unary operator expected

{"success":false,"errors":[{"code":10000,"message":"PUT method not allowed for the api_token authentication scheme"}]}
```

Steps to reproduce:

1) Download script and config
2) Set Zone ID and API Token (DNS Permissions for this zone only)
3) Set domain
4) Run script

**Comment by fire1ce** [comment]
as the error output, api_token authentication scheme is not set corrent. not the script problem.

**Comment by vaughngx4** [comment]
To anyone else who might land here:

Default DNS permissions cannot **create** a record. Creating a record with whatever IP and then running the script works.

**Comment by fire1ce** [comment]
@vaughngx4 

you just had to read the Requirements

![image](https://user-images.githubusercontent.com/16795594/164778983-09d802c3-4583-4e93-b794-35ae5622b9f5.png)

**Comment by vaughngx4** [comment]
@fire1ce Just missed it, apologies. Had bigger fish to fry.
