### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by ptzit** [fire1ce/DDNS-Cloudflare-Bash#5]
root@TESTSRV:~# update-cloudflare-dns
==> 2022-05-26 21:38:05
==> External IP is: 99.88.77.66
==> DNS record of sub.somedomain.tld is: 12.34.56.78. Trying to update...
{"success":false,"errors":[{"code":7003,"message":"Could not route to \/zones\/somedomain.tld\/dns_records, perhaps your object identifier is invalid?"},{"code":7000,"message":"No route for that URI"}],"messages":[],"result":null}
Error! Can't get sub.somedomain.tld record inforamiton from cloudflare API

**Comment by fire1ce** [comment]
Did you create the subdomain recored in cloudflare?

**Comment by ptzit** [comment]
> 

Yes, of course. subdomain was created before I used this script (was experimenting with ddclient prior trying this script).

**Comment by fire1ce** [comment]
To be honest i  didn’t seen this type of error from cloudflare. I suspect it maybe a Access token permission that not allow to get the cloudflare dns zone info.

**Comment by ptzit** [comment]
Tried even global api key but no luck. Rolled the DNS Zone API key and changed in config file - still the same issue happens.

**Comment by fire1ce** [comment]
Deducted Api key. sorry

**Comment by fire1ce** [comment]
thanks. ill test it in the next few days. Not sure about the cause of the error based on the configuration.

**Comment by fire1ce** [comment]
oh i think i spot the problem. your zone ID is not the domain. you have the id number in the dash of cloudflare. this should solve the problem

**Comment by ptzit** [comment]
I found it out by myself too - but now script generates no errors but doesn't update DNS records.

It says success but when I check DNS record on cloudflare dash - nothing changed...

**Comment by ptzit** [comment]
I believe I found out the reason it didn't work for me - Cloudflare dropped API support for Freenom TLDs.

"You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk"

But anyway, let me suggest an edit to the script;
Now, it requires (and uses):
` -H "X-Auth-Email: some@mail.com" \
  -H "X-Auth-Key: sometokenkey" \`

perhaps it could be simpler to use:
`-H "Authorization: Bearer sometokenkey" \`

Thank you for the replies and prompt assistance.
Wish you the best.
