### ISSUE TITLE
Config file as parameter

### ISSUE THREAD

**Issue by lacrimal** [fire1ce/DDNS-Cloudflare-Bash#7]
Hi, 
Found your script very useful.
I know that for multiple domains and single IP I can use CNAME record to set IP once for all.
But having multiple domains and multiple IPs requires probably separate config file.

Could you consider adding config file as parameter with fallback to default one when no parameter presented ?

[EDIT]
As I see it is not working with CNAME records. 
Second idea is multiple domains in dns_record parameter, or maybe both ideas (config file as parameter + multidomain update)

**Comment by fire1ce** [comment]
i can't undersand a thing a thing u are writing. 
if you need multiply ip/dimains run the script in multi instent.

"As I see it is not working with CNAME records."
Never ment to work with cname. cname recored points to domain name. not and ip.

**Comment by lacrimal** [comment]
It is not so difficult to understand.
Your script has external configuration file with fixed name. It is simply overkill to copy same script to different location to run it against different domain because it has fixed name of configuration file.
So that's why suggested adding config file as parameter - then you have one script and multiple config files to use.
Second, you can also modify script to use list of domains a parameter. There will be no need to duplicate it or it's config file until other IP will be used.
About CNAME - it works exactly like you said - IF I have one 'A' record and several aliases as CNAME pointing to it, there is no need to update CNAME - you can update only 'A' record and alias will follow. No need to copy same script over and over.

**Comment by fire1ce** [comment]
Great idea. Unfortunately i don't have time right now to make the changes. If you wish you can post a PR.

**Comment by fire1ce** [comment]
resolved #8 
Thanks @lacrimal  for the PR
